title:              보니 데이터 글방
email:              choila97@gmail.com
description:        옆 동네 데이터 분석가의 글 방앗간
author:             bokyungchoi
baseurl:            ""
url:                "https://bokyungchoi.github.io"

# Social Profiles
github_username:    BokyungChoi
facebook_username:  pagebokyung

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
